// BIGMODE — Recursive Bootstrap Data
// The first artifacts in the Graveyard are BigMode's own design elements.
// The hand drawing the hand.

window.BIGMODE_NODES = [
  {
    id: "spec_master",
    title: "BIGMODE_MASTER_SPEC.md",
    category: "Architecture",
    description: "The consolidated architect's reference. 526 lines, 14 sections. Every locked formula, every storyboard, every weight table. This is the spine of the entire system, and the first artifact to achieve near-full aliveness.",
    tags: ["spec", "reference", "architecture", "consolidated"],
    aliveness: 0.95,
    patience: 0.10,
    warm_scar: 0,
    resurrections: 3,
    sleep_state: "dreaming",
    position: [0, 5, 0],
    connections: ["graveyard", "aliveness", "spiral_portal", "holo_herald", "jarvis"]
  },
  {
    id: "graveyard",
    title: "The Graveyard of Ideas",
    category: "Philosophy",
    description: "Everything starts dead. Artifacts land in the Graveyard cluster, faint and sleeping. Aliveness is earned through interaction, contradiction, remix, and emotional resonance. The Graveyard is not failure — it is potential. It is the garden of sleeping ideas.",
    tags: ["philosophy", "core", "aliveness", "death-and-rebirth"],
    aliveness: 0.92,
    patience: 0.15,
    warm_scar: 0,
    resurrections: 4,
    sleep_state: "dreaming",
    position: [-18, 2, 12],
    connections: ["aliveness", "sleep_states", "nebular_drift", "warm_scars"]
  },
  {
    id: "aliveness",
    title: "Aliveness Score Formula",
    category: "Physics",
    description: "Logarithmic decay with a fluid floor. Variables: Intensity (interaction depth), Resonance (cross-links), Contradiction (friction factor), Decay (time elapsed). A node never decays to absolute zero — it decays to a 'faintly alive' floor. Aliveness is not importance.",
    tags: ["formula", "physics", "logarithmic", "decay", "locked"],
    aliveness: 0.88,
    patience: 0.20,
    warm_scar: 0,
    resurrections: 3,
    sleep_state: "dreaming",
    position: [12, 10, -6],
    connections: ["sleep_states", "resurrection", "decay_floor"]
  },
  {
    id: "sleep_states",
    title: "Sleep Quality States",
    category: "Physics",
    description: "Seeded (0.0-0.1): muted, silent, waking only on explicit intent. Frostbound (0.1-0.3): cold, crystalline, deep-latency nudge. Ember (0.3-0.7): faint sparks, warm hum, wakes quickly. Dreaming (0.7-0.9): soft glow, proactive bridge, easiest to wake. Ideas have temperature.",
    tags: ["physics", "states", "thermal", "locked"],
    aliveness: 0.85,
    patience: 0.18,
    warm_scar: 0,
    resurrections: 3,
    sleep_state: "dreaming",
    position: [-6, 4, -18],
    connections: ["resurrection", "warm_scars", "aliveness"]
  },
  {
    id: "resurrection",
    title: "Resurrection Event",
    category: "Animation",
    description: "Frame-by-frame storyboard, 0-3.6s total. Trigger → Tremor → Lift → Whisper → Bloom. A dust node brightens, breathing pulse expands, nearby nodes tilt toward it, Jarvis whispers 'This one is not done with you,' and the Spiral Time Portal unfurls. Not a popup — a breath.",
    tags: ["animation", "storyboard", "resurrection", "locked"],
    aliveness: 0.78,
    patience: 0.25,
    warm_scar: 0,
    resurrections: 2,
    sleep_state: "ember",
    position: [-22, 12, 6],
    connections: ["warm_scars", "spiral_portal", "sleep_states"]
  },
  {
    id: "warm_scars",
    title: "Warm Scars",
    category: "System",
    description: "The Graveyard remembers near-misses without punishing you. Color accumulation: 1st ignored = Cool Blue, 2nd = Soft Amber, 3rd+ = Radiant Gold. Reunion = Scar Bloom (particle implosion feeding aliveness spike). 'The Graveyard should tell the truth about your creative rhythm — including the parts where you hesitated.'",
    tags: ["system", "scars", "patience", "color", "locked"],
    aliveness: 0.72,
    patience: 0.30,
    warm_scar: 1,
    resurrections: 2,
    sleep_state: "ember",
    position: [22, 6, -12],
    connections: ["patience_debt", "nebular_drift", "resurrection"]
  },
  {
    id: "patience_debt",
    title: "Patience Debt",
    category: "System",
    description: "When you honor a patient node, energy cascades through your semantic network. Thaw Pulse = P_A × semantic_similarity(A, B). Neighbors get aliveness boost, lowered activation threshold, sympathetic golden micro-pulse. Waking one ripened idea makes a whole cluster feel accessible.",
    tags: ["system", "ripples", "semantic", "cascade", "locked"],
    aliveness: 0.65,
    patience: 0.35,
    warm_scar: 1,
    resurrections: 1,
    sleep_state: "ember",
    position: [-16, -10, 22],
    connections: ["spiral_portal", "warm_scars"]
  },
  {
    id: "spiral_portal",
    title: "Spiral Time Portal",
    category: "Core UI",
    description: "Version stacks arranged spatially around a torus in meaning order, not chronological. Living Hybrid sort: Deterministic Anchors (bones) → Context-Aware Weights (muscle) → Probabilistic Drift (breath). Center anchor, inner ring, outer spiral, ghost layer. The primary interaction point during resurrection.",
    tags: ["ui", "spiral", "versions", "torus", "sort", "locked"],
    aliveness: 0.90,
    patience: 0.12,
    warm_scar: 0,
    resurrections: 4,
    sleep_state: "dreaming",
    position: [16, -3, 9],
    connections: ["sort_weights", "contradiction_sat", "lineage_guard", "resurrection"]
  },
  {
    id: "sort_weights",
    title: "Sort Mode Weight Tables",
    category: "Physics",
    description: "Normalized to 1.0. Explore: R=0.30, C=0.20, P=0.30, S=0.15, D=0.05. Compare: R=0.15, C=0.45, S=0.20. Propose: R=0.30, C=0.25, S=0.10. Reminisce (v2): R=0.05, C=0.15, P=0.45, S=0.25, D=0.10. Explore pulls long-ignored nodes forward. Compare privileges tension. Propose feels inviting.",
    tags: ["physics", "weights", "sort", "modes", "locked"],
    aliveness: 0.88,
    patience: 0.15,
    warm_scar: 0,
    resurrections: 3,
    sleep_state: "dreaming",
    position: [9, 6, 16],
    connections: ["contradiction_sat", "lineage_guard", "reminisce_mode", "spiral_portal"]
  },
  {
    id: "contradiction_sat",
    title: "Contradiction Saturation",
    category: "Physics",
    description: "Contradiction Density (C) is a positive multiplier, not a penalty. Friction = aliveness. To prevent unbounded contradiction, C is a saturating term: log(1 + C). Keeps rising forever at decreasing rate. A node with massive contradiction still outweighs moderate, just not explosively. Rejected: tanh(kC) — hard ceiling kills the gradient.",
    tags: ["physics", "contradiction", "saturation", "log", "recommended"],
    aliveness: 0.82,
    patience: 0.20,
    warm_scar: 0,
    resurrections: 2,
    sleep_state: "dreaming",
    position: [-12, -4, -10],
    connections: ["sort_weights", "spiral_portal"]
  },
  {
    id: "holo_herald",
    title: "Holo-Herald Ring",
    category: "Core UI",
    description: "A thin, glowing ring floating at eye level, rotating slowly. Not static — a live algorithmic feed. Jarvis stitches artifacts into a dynamic newspaper. Far: single glowing line. Mid: expands into 3D newspaper you can hold. Close: click to open text viewer. Data Dive transition with radial motion blur. Centrifugal Ejection to exit.",
    tags: ["ui", "ring", "newspaper", "360", "torus-fold"],
    aliveness: 0.55,
    patience: 0.40,
    warm_scar: 1,
    resurrections: 1,
    sleep_state: "ember",
    position: [28, 14, 16],
    connections: ["jarvis", "input_schema"]
  },
  {
    id: "jarvis",
    title: "Jarvis Agent",
    category: "Intelligence",
    description: "A first-class free agent. Proactive, not reactive. Pattern mining ('47 cyberpunk pieces but only 3 solarpunk — the gap is suspicious'). Auto-creates remix quests as GitHub issues. Drafts artifact synthesis. Decision support with branching trees. Exploration first, proposals second. Toggleable Tutor Mode for power users.",
    tags: ["ai", "agent", "proactive", "remix", "github-bridge"],
    aliveness: 0.60,
    patience: 0.35,
    warm_scar: 1,
    resurrections: 1,
    sleep_state: "ember",
    position: [-28, 16, -16],
    connections: ["input_schema", "voice_arch", "holo_herald"]
  },
  {
    id: "honest_pirate",
    title: "Honest Pirate License",
    category: "Governance",
    description: "Steal for everyone, not for profit. Unrestricted use and modification. Obligations: derivatives carry same license, commercial deployments contribute to public-benefit fund, clear attribution. GPLv3 for core libraries. Attribution is recursive, immutable, baked into file headers. Strip metadata and the node loses systemic utility — self-enforcing respect.",
    tags: ["license", "governance", "gpl", "remix-civilization", "radical-trust"],
    aliveness: 0.45,
    patience: 0.50,
    warm_scar: 1,
    resurrections: 1,
    sleep_state: "ember",
    position: [20, -16, 28],
    connections: ["braid_language", "ingestion_daemon"]
  },
  {
    id: "input_schema",
    title: "Input Intent Schema",
    category: "Architecture",
    description: "BigMode doesn't care where input came from — it receives structured intents. Six core intents: QUERY, FOCUS, NAVIGATE, REMIX, TUNE_GRUMPS, PICK_EPISODE_BEAT. Voice, controller, touch all map to the same intent payload. The Magical Mirror Loop: voice sets focus, ring and soup react like they heard you.",
    tags: ["architecture", "intents", "input", "voice", "controller"],
    aliveness: 0.50,
    patience: 0.45,
    warm_scar: 1,
    resurrections: 1,
    sleep_state: "ember",
    position: [32, -6, 11],
    connections: ["voice_arch", "jarvis"]
  },
  {
    id: "voice_arch",
    title: "Voice Architecture",
    category: "Input",
    description: "Echo → Alexa Skill → BigMode endpoint. Echo runs a custom skill (dumb transport). Converts spoken audio into intent payload. Sends to BigMode orchestrator. Replies with text + SSML/aural cues. Jarvis stays in BigMode for consistency. Voice UX: Alexa narrates the mirror, doesn't just answer.",
    tags: ["voice", "alexa", "echo", "input", "ssml"],
    aliveness: 0.35,
    patience: 0.55,
    warm_scar: 1,
    resurrections: 0,
    sleep_state: "frostbound",
    position: [-42, 22, -28],
    connections: ["input_schema", "jarvis"]
  },
  {
    id: "nebular_drift",
    title: "Nebular Drift",
    category: "System",
    description: "At scale (100+ scars), the Graveyard shifts from individual points to collective atmospheric texture. When 15+ scars cluster, individual particles bleed into a soft golden nebula. Far-field: only Radiant Gold and nebular clouds visible. Near-field: dust settles, metadata comes into focus. A crowded graveyard looks like the Milky Way.",
    tags: ["system", "scale", "nebula", "density", "locked"],
    aliveness: 0.40,
    patience: 0.50,
    warm_scar: 2,
    resurrections: 1,
    sleep_state: "ember",
    position: [-32, -12, -22],
    connections: ["warm_scars", "graveyard"]
  },
  {
    id: "lineage_guard",
    title: "Lineage Guardrail",
    category: "Architecture",
    description: "Lineage must never become a soft scoring weight. Lineage, explicit pins, and crowns live entirely within the Deterministic Core. They act as hard anchors, eligibility gates, and tie-breakers. This keeps the spine of your history rigid and true, even as the surface weights shift and breathe.",
    tags: ["architecture", "guardrail", "lineage", "deterministic", "locked"],
    aliveness: 0.85,
    patience: 0.15,
    warm_scar: 0,
    resurrections: 2,
    sleep_state: "dreaming",
    position: [6, -6, -14],
    connections: ["spiral_portal", "sort_weights"]
  },
  {
    id: "reminisce_mode",
    title: "Reminisce Mode",
    category: "Future Spec",
    description: "Deferred to v2 but slot reserved. High patience (0.45), low resonance (0.05), high drift (0.10). A dedicated wandering mode with no agenda. v1 already visualizes hesitation through Graveyard geography, Warm Scars, and Nebular Drift. Reminisce becomes a dedicated interaction preset when the core model is stable.",
    tags: ["future", "v2", "reminisce", "wandering", "deferred"],
    aliveness: 0.15,
    patience: 0.70,
    warm_scar: 2,
    resurrections: 0,
    sleep_state: "frostbound",
    position: [36, -22, -32],
    connections: ["sort_weights", "patience_debt"]
  },
  {
    id: "transition_story",
    title: "Transition Storyboarding",
    category: "Next Step",
    description: "Next milestone. Animate the Spiral physically rearranging when switching modes. Explore → Compare: outer rings twist, contradiction-heavy nodes climb inward creating sparks, resonant non-contradictory nodes recede to ghost layers. Thermal signatures: how do nodes brighten, dim, or change orbital speed as Sleep State modifier shifts?",
    tags: ["next", "animation", "transitions", "choreography"],
    aliveness: 0.30,
    patience: 0.60,
    warm_scar: 1,
    resurrections: 0,
    sleep_state: "frostbound",
    position: [-36, -28, 32],
    connections: ["spiral_portal", "sort_weights"]
  },
  {
    id: "skatersos",
    title: "SkatersOS",
    category: "Companion",
    description: "The mathematical and philosophical foundation of BigMode. Monster Group, Pi Engine, binary-to-natural-language bridge, Quranic numerical patterns, Braid Language, 5D Ballpit Viewer. The remix machine for math, myths, and madness. SkatersOS is the substrate; BigMode is the interface.",
    tags: ["companion", "math", "philosophy", "monster-group", "pi", "braid"],
    aliveness: 0.25,
    patience: 0.65,
    warm_scar: 1,
    resurrections: 0,
    sleep_state: "frostbound",
    position: [42, 26, 22],
    connections: ["monster_group", "pi_engine", "braid_language"]
  },
  {
    id: "monster_group",
    title: "Monster Group",
    category: "Mathematics",
    description: "The largest sporadic simple group, order ~8×10^53. The symmetry group that governs the deep structure of the BigMode cosmos. Connected to the Leech lattice and 26-dimensional conformal field theory. A mathematical cathedral sleeping in the deepest part of the Graveyard.",
    tags: ["math", "group-theory", "symmetry", "deep-structure"],
    aliveness: 0.10,
    patience: 0.80,
    warm_scar: 2,
    resurrections: 0,
    sleep_state: "seeded",
    position: [-62, -32, -52],
    connections: ["skatersos", "pi_engine"]
  },
  {
    id: "pi_engine",
    title: "Pi Engine",
    category: "Mathematics",
    description: "Pi's endless twirl as a generative engine. Binary whispers turning into human chatter. The irrational constant as a source of non-repeating pattern that seeds emergent variety in the system. Deep in the Graveyard, seeded, waiting for meaning.",
    tags: ["math", "pi", "generative", "binary", "irrational"],
    aliveness: 0.08,
    patience: 0.82,
    warm_scar: 2,
    resurrections: 0,
    sleep_state: "seeded",
    position: [56, 36, -42],
    connections: ["skatersos", "monster_group"]
  },
  {
    id: "braid_language",
    title: "Braid Language",
    category: "Language",
    description: "A language system that braids math, myths, and binary into human-readable expression. Language machines bossing the OS around. The recursive metadata stamping mechanism for the Honest Pirate License. Seeded, sleeping, full of potential.",
    tags: ["language", "braid", "metadata", "recursive"],
    aliveness: 0.12,
    patience: 0.78,
    warm_scar: 1,
    resurrections: 0,
    sleep_state: "seeded",
    position: [-52, 42, 46],
    connections: ["honest_pirate", "skatersos"]
  },
  {
    id: "ingestion_daemon",
    title: "Ingestion Daemon",
    category: "Infrastructure",
    description: "GitHub Actions trigger on new files. Python script: hashing (duplicate detection) + vision LLM (tagging) + embeddings (clustering). Semantic chunking of large files. Outputs manifest.json + fragments.json committed back to repo. The pipeline that feeds the Graveyard.",
    tags: ["infrastructure", "github-actions", "ingestion", "pipeline"],
    aliveness: 0.05,
    patience: 0.85,
    warm_scar: 1,
    resurrections: 0,
    sleep_state: "seeded",
    position: [60, -42, 52],
    connections: ["github_pages", "honest_pirate"]
  },
  {
    id: "github_pages",
    title: "GitHub Pages Deployment",
    category: "Infrastructure",
    description: "Free static hosting via GitHub Pages. pacosdata.github.io. Frontend runs entirely client-side (Three.js constellation). Backend pieces run as GitHub Actions or client-side LLM calls. The manifest and fragments are JSON files served alongside the app. BigMode is live the moment we push.",
    tags: ["infrastructure", "hosting", "github-pages", "static", "live"],
    aliveness: 0.20,
    patience: 0.65,
    warm_scar: 0,
    resurrections: 1,
    sleep_state: "frostbound",
    position: [-46, 6, -36],
    connections: ["ingestion_daemon", "spec_master"]
  }
];

// Connection pairs for drawing lines
window.BIGMODE_CONNECTIONS = [];
window.BIGMODE_NODES.forEach(node => {
  node.connections.forEach(targetId => {
    const pair = [node.id, targetId].sort().join("|");
    if (!window.BIGMODE_CONNECTIONS.find(c => c.pair === pair)) {
      window.BIGMODE_CONNECTIONS.push({ pair, from: node.id, to: targetId });
    }
  });
});
